find_package(libENSEMBLE REQUIRED COMPONENTS
  HINTS ${LIBENSEMBLE_DIR} $ENV{LIBENSEMBLE_DIR} ${CMAKE_PREFIX_PATH}
  NO_DEFAULT_PATH)

if(NOT TARGET XSDK::libENSEMBLE)
  add_library(XSDK_LIBENSEMBLE INTERFACE)
  target_link_libraries(XSDK_LIBENSEMBLE INTERFACE libENSEMBLE::libensemble)
  add_library(XSDK::libENSEMBLE ALIAS XSDK_LIBENSEMBLE)
endif()

